# This file was generated by GoReleaser. DO NOT EDIT.
cask "comsarif" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a97fcda5b487c3c512cbdf1bbfb7f8969d966e4545da5cc1b1c1b3e1ff9246b3"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cd509b1b4720e0ab0e29ed3872af3c8854b7312b6a6ab7025febd2f19fef7281"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6c2e4e2e1a334184b6434674a48777a33f77da3a8aec54365bdc888541262f6"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "07b4715823889ede0b460b7aa9d86d6757fd2d3445a8881693cd0c5f7218e795"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Linux_arm64.tar.gz"
    end
  end

  name "comsarif"
  desc "Convert Composer audit reports to SARIF files"
  homepage "https://github.com/typisttech/comsarif"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comsarif"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/comsarif"]
    end
  end

  # No zap stanza required

end
