# This file was generated by GoReleaser. DO NOT EDIT.
cask "comsarif" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "609ce54b433cf8c5414eaabeb98b18d18c2dbb565016241cac30fc5500e3a039"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a43b0253a18b61868d102ad3e4039429bdc1e4249072e2aa4591ef66eaabd631"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "09f0f3a181e155967401d37aacf621ab18310c7434c342a3fe2dcb07c266cef3"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4643b94e43fc45e3d2f92867b1991e6475f1219094cf23eade355ddec37d7a0f"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Linux_arm64.tar.gz"
    end
  end

  name "comsarif"
  desc "Convert Composer audit reports to SARIF files"
  homepage "https://github.com/typisttech/comsarif"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comsarif"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/comsarif"]
    end
  end

  # No zap stanza required

end
