# This file was generated by GoReleaser. DO NOT EDIT.
cask "comsarif" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "084d5357bdf9a8b7b9268d2aa7a8a98b470b203cfa2607b8a7cfc34348f35817"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "abf2c59709ef755d99832c574017cd98bf935909da0c6b10091cfafd4782d25e"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4eef266420e73dd60ae3ab2bb59c283b018b2d22da135b50bffd4ac72cb0ccfb"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3a3ee63843c042413a2d2b2543171044a5ab244c9e09e9b3d98e84f1637539fd"
      url "https://github.com/typisttech/comsarif/releases/download/v#{version}/comsarif_Linux_arm64.tar.gz"
    end
  end

  name "comsarif"
  desc "Convert Composer audit reports to SARIF files"
  homepage "https://github.com/typisttech/comsarif"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comsarif"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/comsarif"]
    end
  end

  # No zap stanza required

end
