# This file was generated by GoReleaser. DO NOT EDIT.
cask "php-matrix" do
  version "1.1.6"

  on_macos do
    on_intel do
      sha256 "c59b9fcb6c8863d1860211301a66142d1d8fa8fb8061a7620d473e33a2dc43c2"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "19d2dad3c84132d3bc4e099a3049fe47175d67eadb9fbe64b32379d34b90c4af"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba1850aedcfd1ea3338133b0aa4b7b18476044206ed6a876d04fd65082ab8d07"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3266d8e00ad9eede494074a1bc378ad08a66d9602de2bdab865a33c0f0ea9029"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Linux_arm64.tar.gz"
    end
  end

  name "php-matrix"
  desc "List PHP versions that satisfy the required PHP constraint in composer.json"
  homepage "https://github.com/typisttech/php-matrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "php-matrix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/php-matrix"]
    end
  end

  # No zap stanza required

end
