# This file was generated by GoReleaser. DO NOT EDIT.
cask "php-matrix" do
  version "1.1.5"

  on_macos do
    on_intel do
      sha256 "c32359cae840aff32ccb941be92dd5b517aec3a8197ed85fec8a2420e8d39318"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "98d4aaaf0040320bf46610af377863ee9dcf95a4688a51d829f2494b4937a007"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "060e2c80706e4d68d9483487a4704ce9dbf1b9af004b3452a38d43f9062e4484"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "874377156c3561a887a9eee8b088bda6e799aa98fb9848cef81be4463cfb6be3"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Linux_arm64.tar.gz"
    end
  end

  name "php-matrix"
  desc "List PHP versions that satisfy the required PHP constraint in composer.json"
  homepage "https://github.com/typisttech/php-matrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "php-matrix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/php-matrix"]
    end
  end

  # No zap stanza required

end
