# This file was generated by GoReleaser. DO NOT EDIT.
cask "php-matrix" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "2c70950535c8c502a9a2ee20ad844ad3a162bcaa0fc63772ed2edb359e2d7b4c"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "645afa07803bdf051568b3ad8e79549a976573021a3cc54247ac90a4ae967ecb"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06228d583673500f4d93e93d12481b940b6b29f3ea95b06bf384c2442f42d08d"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "372c76c5164cfe545b72dc5527132afbeae6f846b11a9e9c959ad575ebfe746f"
      url "https://github.com/typisttech/php-matrix/releases/download/v#{version}/php-matrix_Linux_arm64.tar.gz"
    end
  end

  name "php-matrix"
  desc "List PHP versions that satisfy the required PHP constraint in composer.json"
  homepage "https://github.com/typisttech/php-matrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "php-matrix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/php-matrix"]
    end
  end

  # No zap stanza required

end
