# This file was generated by GoReleaser. DO NOT EDIT.
cask "wpry" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "a17c805c7e7ac5922ddafab2c1fffde0dfd62ed448784aa13faf367d12420fc1"
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8486ab3c4dcc9812337fbcac0b4ff2abec2909a4b211cc30a910b122ddb05c48"
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ebada051c597e246a42d65a386c0ae296b73265fccbca0cc6e2c37a41bd84750"
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3169e2dddefd50da919ce36d1def1b887e53f4bd6f9245e8fb0a23124c256496"
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Linux_arm64.tar.gz"
    end
  end

  name "wpry"
  desc "Parses WordPress plugin and theme headers"
  homepage "https://github.com/typisttech/wpry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wpry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wpry"]
    end
  end

  # No zap stanza required

end
