# This file was generated by GoReleaser. DO NOT EDIT.
cask "wpry" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Darwin_x86_64.tar.gz"
      sha256 "25e04e82153b5387c3c848fe7bedcc5eb1c83097d08ebdd43042fffbfee18630"
    end
    on_arm do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Darwin_arm64.tar.gz"
      sha256 "f2f4b7a39b24a66da8624239eae3c45df29ac07b955c710e7dd8fb67c02eaaf2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Linux_x86_64.tar.gz"
      sha256 "6345c2110663292170a504b467e4f77cd8eaa3407aaebb1d7498458480be31ac"
    end
    on_arm do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Linux_arm64.tar.gz"
      sha256 "0dd0154e248b3d5bfff1d0760a4ca1d5c56f39ab19bb2a02b0b33e761058ac17"
    end
  end

  name "wpry"
  desc "Parses WordPress plugin and theme headers"
  homepage "https://github.com/typisttech/wpry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wpry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wpry"]
    end
  end

  # No zap stanza required

end
