# This file was generated by GoReleaser. DO NOT EDIT.
cask "wpry" do
  version "0.0.10"

  on_macos do
    on_intel do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Darwin_x86_64.tar.gz"
      sha256 "9a24685a29edaac7bf7760df344439ba402b7d694079e1d59a670fab8396727d"
    end
    on_arm do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Darwin_arm64.tar.gz"
      sha256 "275121c14fd594cd7bc18f7ae64365877dc49fe657b2aebd623a843c692d3974"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Linux_x86_64.tar.gz"
      sha256 "55062534aac147beefdf273e7407b67ce1451ae290e7f07fb622c1d68fe99f2a"
    end
    on_arm do
      url "https://github.com/typisttech/wpry/releases/download/v#{version}/wpry_Linux_arm64.tar.gz"
      sha256 "5bfcd730627c70ae1672d306c3696ff99754a2ddfa97ac9d7465eaa6eee6bc2f"
    end
  end

  name "wpry"
  desc "Parses WordPress plugin and theme headers."
  homepage "https://github.com/typisttech/wpry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wpry"

  # No zap stanza required

end
