# DO NOT EDIT THIS FILE
# This file is generated by "internal/formula/composer-semver/main.go"
class ComposerSemver < Formula
  desc "Static linked CLI wrapper for composer/semver"
  homepage "https://github.com/typisttech/composer-semver"
  version "0.6.1"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest do |json, regex|
      match = json["tag_name"]&.match(regex)
      next if match.blank?

      match[1]
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.6.1/composer-semver_Darwin_arm64.tar.gz"
      sha256 "1130269f1b80205fad9af43a31ad36fc00e5c08f7034adc37a5faee1a0d9b611"
    end
    if Hardware::CPU.intel?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.6.1/composer-semver_Darwin_amd64.tar.gz"
      sha256 "5f673fec791a0b6f8cd818182d2cc2ff6d4958097194b038e8018f7b23b8c3e1"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.6.1/composer-semver_Linux_arm64.tar.gz"
      sha256 "b5f530ec211c7cc0f485a46b39cff69ae9500a7e5484effb50f0b45f5608a10f"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.6.1/composer-semver_Linux_amd64.tar.gz"
      sha256 "4f14085132e54e46d2af886a444f954efc896307fdbcfe717cd19535764e8713"
    end
  end

  def install
    bin.install "composer-semver"
    generate_completions_from_executable(bin/"composer-semver", "completion")
  end

  test do
    assert_match "Composer SemVer v0.6.1", shell_output("#{bin}/composer-semver --version")
  end
end
