# DO NOT EDIT THIS FILE
# This file is generated by "internal/formula/composer-semver/main.go"
class ComposerSemver < Formula
  desc "Static linked CLI wrapper for composer/semver. Parsing and validating versions exactly like Composer does without installing PHP."
  homepage "https://github.com/typisttech/composer-semver"
  version "0.4.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.4.8/composer-semver_Darwin_arm64.tar.gz"
      sha256 "6725a351833ac1bcb83f30a2978224f2d17f8408ca27871086246661c75aa76b"
    end
    if Hardware::CPU.intel?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.4.8/composer-semver_Darwin_amd64.tar.gz"
      sha256 "fd40a79eb93b5ef3125a6c5fe28c1450151ae12e849735914128f63278e6e7fb"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.4.8/composer-semver_Linux_arm64.tar.gz"
      sha256 "8b0d9ee57c9651d002ceb04f9a619f900e114cfb00a4b138e17eaa23fd8ada4d"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.4.8/composer-semver_Linux_amd64.tar.gz"
      sha256 "4596c5ef4f632935aa3f9f5f603ffe04a5d80109f35e4507aa70330f01a045df"
    end
  end

  def install
    bin.install "composer-semver"
    generate_completions_from_executable(bin/"composer-semver", "completion")
  end

  test do
    assert_match "Composer SemVer v0.4.8", shell_output("#{bin}/composer-semver --version")
  end
end
