# DO NOT EDIT THIS FILE
# This file is generated by "internal/formula/composer-semver/main.go"
class ComposerSemver < Formula
  desc "Static linked CLI wrapper for composer/semver"
  homepage "https://github.com/typisttech/composer-semver"
  version "0.5.0"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest do |json, regex|
      match = json["tag_name"]&.match(regex)
      next if match.blank?

      match[1]
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.5.0/composer-semver_Darwin_arm64.tar.gz"
      sha256 "a7caa15a071e344c38042ea249f4cf3478ebfc86cab912dba29f14a75d6d889b"
    end
    if Hardware::CPU.intel?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.5.0/composer-semver_Darwin_amd64.tar.gz"
      sha256 "607e3a786d2420f7e90e07d72689ad5b0de485ff02fba33a76ebafc7c75427e3"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.5.0/composer-semver_Linux_arm64.tar.gz"
      sha256 "a1fd640ca2804728d4fc73ab3f0076c17fc358dcb4882ea940020fa1927abd63"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/composer-semver/releases/download/v0.5.0/composer-semver_Linux_amd64.tar.gz"
      sha256 "86226d582913cefe810f31bf1175ecc46806dd10d784180663c28d1a548cb726"
    end
  end

  def install
    bin.install "composer-semver"
    generate_completions_from_executable(bin/"composer-semver", "completion")
  end

  test do
    assert_match "Composer SemVer v0.5.0", shell_output("#{bin}/composer-semver --version")
  end
end
