# DO NOT EDIT THIS FILE
# This file is generated by "internal/formula/php-matrix/main.go"
class PhpMatrix < Formula
  desc "List PHP versions that satisfy the given constraint"
  homepage "https://github.com/typisttech/php-matrix"
  version "1.0.4"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest do |json, regex|
      match = json["tag_name"]&.match(regex)
      next if match.blank?

      match[1]
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.4/php-matrix_darwin_arm64.tar.gz"
      sha256 "befcd921c027185efc77b9e5e40151a20e6ac352c8ff1076a9f1a0e895d233a2"
    end
    if Hardware::CPU.intel?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.4/php-matrix_darwin_amd64.tar.gz"
      sha256 "49ce43e4b5d89e432aa4328a09be294c5c2a3111a4be0e6bfef9d06637ecf20b"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.4/php-matrix_linux_arm64.tar.gz"
      sha256 "a6757b67452dcf58ba06e2c38eb40587f5093ee197caa4dfa134f8c0b005a9d2"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.4/php-matrix_linux_amd64.tar.gz"
      sha256 "798a48669ab546003a639500517da075a949bd5198d6c52fffd4fae477b42281"
    end
  end

  def install
    bin.install "php-matrix"
    generate_completions_from_executable(bin/"php-matrix", "completion")
  end

  test do
    regex = /PHP Matrix\s+v1.0.4/
    assert_match regex, shell_output("#{bin}/php-matrix --version")
  end
end
