# DO NOT EDIT THIS FILE
# This file is generated by "internal/formula/php-matrix/main.go"
class PhpMatrix < Formula
  desc "List PHP versions that satisfy the required PHP constraint in composer.json"
  homepage "https://github.com/typisttech/php-matrix"
  version "1.0.10"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest do |json, regex|
      match = json["tag_name"]&.match(regex)
      next if match.blank?

      match[1]
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.10/php-matrix_darwin_arm64.tar.gz"
      sha256 "65e8300433874d0b12a7b4362813f459e6c3fd03aa7703abcdbe4b2dae522951"
    end
    if Hardware::CPU.intel?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.10/php-matrix_darwin_amd64.tar.gz"
      sha256 "216d89774052359c4ec3a1ec57d95c3c8ecb66b224769a82a1f48b8fa37957be"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.10/php-matrix_linux_arm64.tar.gz"
      sha256 "9bac87ccedf84717279724ebd6126118ac6e58717cc6144ec79160adb49a9512"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.10/php-matrix_linux_amd64.tar.gz"
      sha256 "8ca56355d9e872122a16f3233a46818c14175c0112bbb2bb083dc725a6a40ddc"
    end
  end

  def install
    bin.install "php-matrix"
    generate_completions_from_executable(bin/"php-matrix", "completion")
  end

  test do
    regex = /PHP Matrix\s+v1.0.10/
    assert_match regex, shell_output("#{bin}/php-matrix --version")
  end
end
