# DO NOT EDIT THIS FILE
# This file is generated by "internal/formula/php-matrix/main.go"
class PhpMatrix < Formula
  desc "List PHP versions that satisfy the required PHP constraint in composer.json"
  homepage "https://github.com/typisttech/php-matrix"
  version "1.0.12"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest do |json, regex|
      match = json["tag_name"]&.match(regex)
      next if match.blank?

      match[1]
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.12/php-matrix_darwin_arm64.tar.gz"
      sha256 "2df8fa98d66272a8713c06f7b95eaefa6b8e2dfaf5c7b365e2b325f1016f2075"
    end
    if Hardware::CPU.intel?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.12/php-matrix_darwin_amd64.tar.gz"
      sha256 "6114da83c6028d00ea927b2bf7ea986534d1b0dfc85d78a06035f02a00cbb27d"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.12/php-matrix_linux_arm64.tar.gz"
      sha256 "291196d433350e50990b05b7260d5829f36db7cc3eda2904b6f28b616a29b572"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typisttech/php-matrix/releases/download/v1.0.12/php-matrix_linux_amd64.tar.gz"
      sha256 "2055722be3bc5023c60ae2d79fb8b8b7f05186a2df75ad7e788aae0b5f3b79c6"
    end
  end

  def install
    bin.install "php-matrix"
    generate_completions_from_executable(bin/"php-matrix", "completion")
  end

  test do
    regex = /PHP Matrix\s+v1.0.12/
    assert_match regex, shell_output("#{bin}/php-matrix --version")
  end
end
