name: Update formulae

on:
  workflow_dispatch:
  schedule:
    - cron: 5 6 * * 1 # Weekly on Monday
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - run: go generate ./...

      - uses: typisttech/.github/.github/actions/create-auto-merged-pull-request@v3
        with:
          app-id: ${{ vars.TASTENDRUCK_APP_ID }}
          private-key: ${{ secrets.TASTENDRUCK_PRIVATE_KEY }}
          branch: "tastendruck/github_actions/go-generate/${{ github.ref_name }}"
          title: ":robot: `go generate ./...`"
          labels: go-generate
